version: '3.8'
services:
  app:
    image: sloopstash/nodejs-app:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    ports:
      - "8080:8080"
    volumes:
      - /opt/kickstart-docker/app:/opt/app/source
      - /opt/kickstart-docker/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/kickstart-docker/supervisor/conf/nodejs.ini:/etc/supervisord.d/nodejs.ini
    depends_on:
      - mongodb
    networks:
      common:
        ipv4_address: 100.3.1.10
  mongodb:
    image: sloopstash/mongodb2:v1
    command: "/usr/bin/supervisord -c /etc/supervisord.conf"
    volumes:
      - mongodb-data:/opt/mongodb/data
      - mongodb-log:/opt/mongodb/log
      - /opt/kickstart-docker/mongodb/conf/mongod.conf:/opt/mongodb/conf/mongod.conf
      - /opt/kickstart-docker/supervisor/conf/main.conf:/etc/supervisord.conf
      - /opt/kickstart-docker/supervisor/conf/mongodb.ini:/etc/supervisord.d/mongodb.ini
    networks:
      common:
        ipv4_address: 100.3.1.20
volumes:
  mongodb-data:
    driver: local
  mongodb-log:
    driver: local
networks:
  common:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 100.3.0.0/16
